buffer_size: 60 # number of frames to average
behaviors:
  - name: default
    enabled: false # Change this to false to disable this behavior
    arduino_command: default
    parameters:
      time:
        enabled: true
        timeout: 300 # run every 10 minutes
      people:
        enabled: true
        min: 2 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 100
      groups:
        enabled: false
        min: 0
        max: 10
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0.3
      avg_distance_between_people:
        enabled: false
        min: 80
        max: 150
      avg_distance_from_machine:
        enabled: false
        min: 150
        max: 400
  - name: glitch
    enabled: true # Change this to false to disable this behavior
    arduino_command: glitch
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 15 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 100
      groups:
        enabled: false
        min: 0
        max: 10
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0.3
      avg_distance_between_people:
        enabled: false
        min: 1
        max: 60
      avg_distance_from_machine:
        enabled: true
        min: 250
        max: 280
  - name: quiver
    enabled: true # Change this to false to disable this behavior
    arduino_command: quiver
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 30 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 200
      groups:
        enabled: false
        min: 0
        max: 0
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0
      avg_distance_between_people:
        enabled: false
        min: 10
        max: 300
      avg_distance_from_machine:
        enabled: true
        min: 280
        max: 310
  - name: undulate
    enabled: true # Change this to false to disable this behavior
    arduino_command: undulate
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 1 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 100
      groups:
        enabled: false
        min: 0
        max: 0
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0
      avg_distance_between_people:
        enabled: false
        min: 0
        max: 400
      avg_distance_from_machine:
        enabled: true
        min: 310
        max: 340
  - name: breathe
    enabled: true # Change this to false to disable this behavior
    arduino_command: breathe
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 1 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 50
      groups:
        enabled: false
        min: 0
        max: 0
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0
      avg_distance_between_people:
        enabled: false
        min: 0
        max: 300
      avg_distance_from_machine:
        enabled: true
        min: 340
        max: 370