buffer_size: 60 # number of frames to average
behaviors:
  - name: default
    enabled: true
    arduino_command: default
    parameters:
      time:
        enabled: true
        timeout: 600 # run every 10 minutes
      people:
        enabled: false
        min: 2 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 10
      groups:
        enabled: false
        min: 0
        max: 10
      people_in_groups_ratio:
        enabled: false
        min: 0
        max: 0.3
      avg_distance_between_people:
        enabled: false
        min: 80
        max: 150
      avg_distance_from_machine:
        enabled: false
        min: 150
        max: 400
  - name: breathe
    enabled: true
    arduino_command: breathe
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 0 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 10
      groups:
        enabled: false
        min: 0
        max: 10
      people_in_groups_ratio:
        enabled: false
        min: 0
        max: 0.3
      avg_distance_between_people:
        enabled: true
        min: 0
        max: 150
      avg_distance_from_machine:
        enabled: true
        min: 0
        max: 400
  - name: quiver
    enabled: true
    arduino_command: quiver
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 2 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 5
      groups:
        enabled: true
        min: 0
        max: 10
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0.3
      avg_distance_between_people:
        enabled: true
        min: 40
        max: 100
      avg_distance_from_machine:
        enabled: true
        min: 150
        max: 400
  - name: undulate
    enabled: true
    arduino_command: undulate
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 2 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 10
      groups:
        enabled: true
        min: 1
        max: 10
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0.3
      avg_distance_between_people:
        enabled: true
        min: 20
        max: 150
      avg_distance_from_machine:
        enabled: true
        min: 150
        max: 400
  - name: glitch
    enabled: true
    arduino_command: glitch
    parameters:
      time:
        enabled: false
        timeout: 600 # run every 10 minutes
      people:
        enabled: true
        min: 2 # Absolute value vs relative to the avg number of people in the last minute or so
        max: 10
      groups:
        enabled: true
        min: 0
        max: 10
      people_in_groups_ratio:
        enabled: true
        min: 0
        max: 0.3
      avg_distance_between_people:
        enabled: true
        min: 80
        max: 150
      avg_distance_from_machine:
        enabled: true
        min: 150
        max: 400