url: "wss://anthropomorphicmachine.com"
sockets:
  - id: "GAL_PROD"
    enabled: false
    namespace: "/gallery_stream"
    type: 'video_stream_out'
    port: 3005
    sync_with_server: false
    send_frames: true
    frame_scaling: true
    frame_adaptive: false
    min_frame_scaling: 0.5 # adaptive fame scaling
    fixed_frame_scaling: 0.5
    frame_skip: true
    target_framerate: 25
    emit_event: 'gallery_stream_in'

  - id: "GAL_DEV"
    enabled: true
    namespace: "/gallery_stream"
    type: 'video_stream_out'
    port: 3006
    sync_with_server: false
    send_frames: true
    frame_scaling: true
    frame_adaptive: false
    min_frame_scaling: 0.5 # adaptive fame scaling
    fixed_frame_scaling: 0.5
    frame_skip: true
    target_framerate: 25
    emit_event: 'gallery_stream_in'

  - id: "OI_PROD"
    enabled: false
    namespace: "/online_interaction"
    type: 'online_interaction'
    port: 3005
    sync_with_server: false
    emit_event: 'remote_interaction_update'

  - id: "OI_DEV"
    enabled: true
    namespace: "/online_interaction"
    type: 'online_interaction'
    port: 3006
    sync_with_server: false
    emit_event: 'remote_interaction_update'
